(() => {
  const englishPath = location.pathname;
  const persianPath = englishPath.replace(/^\/en\//, "/");
  const persianUrl = `${persianPath}${location.search}${location.hash}`;
  const ltrStyles = document.createElement("link");
  ltrStyles.rel = "stylesheet";
  ltrStyles.href = "en/en.css";
  document.head.appendChild(ltrStyles);
  const translations = new Map(Object.entries({
    "تجهیزات دقیق": "Precision Equipment",
    "برای تولید بدون توقف": "for Uninterrupted Production",
    "طراحی و ساخت تجهیزات فیلتراسیون و فرایندی متناسب با سیال، ظرفیت و شرایط واقعی خط تولید شما.": "Filtration and process equipment engineered around your fluid, capacity, and actual production-line conditions.",
    "درخواست بررسی فنی": "Request a Technical Review",
    "مشاهده محصولات": "View Products",
    "کندل فیلتر": "Candle Filter",
    "سیستم فیلتراسیون صنعتی": "Industrial Filtration System",
    "فیلتر شمعی": "Candle Filtration",
    "فیلتر کارتریج": "Cartridge Filter",
    "فیلتراسیون دقیق": "Precision Filtration",
    "دی‌اریتور آب سرد": "Cold-Water Deaerator",
    "حذف اکسیژن محلول": "Dissolved-Oxygen Removal",
    "مونوپمپ": "Progressing Cavity Pump",
    "انتقال سیالات غلیظ": "Viscous-Fluid Transfer",
    "تماس": "Contact",
    "استعلام فنی و قیمت": "Technical & Pricing Enquiry",
    "محصولات / فیلتراسیون": "Products / Filtration",
    "محصولات / تجهیزات فرایندی": "Products / Process Equipment",
    "محصولات / پمپ‌های صنعتی": "Products / Industrial Pumps",
    "درخواست پیشنهاد فنی ←": "Request a Technical Proposal →",
    "تماس با واحد فروش": "Call Sales",
    "معرفی دستگاه": "Equipment Overview",
    "کاربردها": "Applications",
    "مزایا": "Advantages",
    "جدول مشخصات فنی": "Technical Specifications",
    "نوع سیستم": "System Type",
    "سطح اتوماسیون": "Automation Level",
    "دسترسی سریع": "Quick Navigation",
    "اطلاعات موردنیاز انتخاب": "Selection Requirements",
    "عوامل مؤثر بر قیمت": "Pricing Factors",
    "استعلام براساس مشخصات خط": "Request a Line-Specific Quotation",
    "صفحات مرتبط": "Related Pages",
    "تمام محصولات": "All Products",
    "سبد تجهیزات بهریز مبدل": "Behriz Mobadel Equipment Portfolio",
    "خط تولید نوشیدنی": "Beverage Production Line",
    "طراحی تجهیزات فرایندی خط": "Production-Line Process Engineering",
    "فیلتراسیون نوشیدنی": "Beverage Filtration",
    "کندل فیلتر صنعتی": "Industrial Candle Filter",
    "کندل فیلتر بهریز مبدل یک سیستم فیلتراسیون تحت فشار با فرایند Precoat است که برای شفاف‌سازی و حذف کدورت و ناخالصی مایعات طراحی می‌شود. ذرات باقی‌مانده روی المنت‌ها در چرخه شست‌وشوی معکوس از فیلتر جدا می‌شوند و طراحی نهایی دستگاه متناسب با محصول و شرایط واقعی خط انجام می‌گیرد.": "The Behriz Mobadel candle filter is a pressurised precoat filtration system designed to clarify liquids and remove haze and impurities. Retained particles are released from the elements during the backwash cycle, while the final system is engineered around the product and actual line conditions.",
    "فیلتراسیون تحت فشار برای خروجی شفاف و پایدار": "Pressurised Filtration for a Clear, Consistent Output",
    "در فرایند Precoat، لایه اولیه‌ای از ماده کمک‌فیلتر روی کندل‌ها تشکیل می‌شود. سیال تحت فشار از این بستر عبور می‌کند و ذرات عامل کدورت در لایه فیلتر نگه داشته می‌شوند. دبی، اختلاف فشار، زمان هر سیکل و شرایط شست‌وشو براساس نوع سیال و کیفیت خروجی مورد انتظار تنظیم می‌شوند.": "In the precoat process, an initial layer of filter aid is formed on the candles. Pressurised fluid passes through this bed and haze-forming particles are retained. Flow rate, differential pressure, cycle duration and cleaning conditions are configured for the fluid and required outlet quality.",
    "مناسب خطوط صنایع غذایی و نوشیدنی": "For Food & Beverage Production Lines",
    "این دستگاه برای فیلتراسیون و شفاف‌سازی شربت، محلول‌های قندی، آبمیوه، ماءالشعیر و سایر مایعات صنایع غذایی و آشامیدنی، پس از بررسی مشخصات فنی محصول، طراحی و ساخته می‌شود.": "This system is designed and manufactured for filtration and clarification of syrup, sugar solutions, juice, malt beverages and other food and beverage liquids after a technical review of the product.",
    "مزیت‌های کندل فیلتر بهریز مبدل": "Advantages of the Behriz Mobadel Candle Filter",
    "شفاف‌سازی و حذف کدورت و ناخالصی‌ها": "Clarification and removal of haze and impurities",
    "راندمان بالای فیلتراسیون": "High filtration efficiency",
    "تعمیر و نگهداری آسان": "Straightforward service and maintenance",
    "هزینه پایین مواد مصرفی": "Low consumables cost",
    "قابلیت طراحی برای CIP و Backwash": "Configurable for CIP and backwash",
    "امکان نصب Turbidimeter روی مسیر آنلاین": "Optional online turbidimeter",
    "ساخت نیمه‌اتوماتیک یا تمام‌اتوماتیک": "Semi-automatic or fully automatic build",
    "طراحی ظرفیت متناسب با فرایند مشتری": "Capacity engineered for the customer process",
    "۴٬۰۰۰ تا ۴۰٬۰۰۰ لیتر در ساعت": "4,000–40,000 L/h",
    "جنس مخزن و فرمات": "Vessel & Frame Material",
    "جنس کندل": "Candle Material",
    "نیمه‌اتوماتیک یا تمام‌اتوماتیک": "Semi-Automatic or Fully Automatic",
    "سیستم شست‌وشو": "Cleaning System",
    "قابل طراحی برای CIP و Backwash": "Configurable for CIP and Backwash",
    "ابزار پایش": "Monitoring",
    "قابلیت نصب Turbidimeter آنلاین": "Optional Online Turbidimeter",
    "مشخصات نهایی، ابعاد، تعداد کندل‌ها و تجهیزات جانبی براساس نوع سیال، ظرفیت، شرایط خط و کیفیت خروجی مورد انتظار تعیین می‌شوند.": "Final specifications, dimensions, candle count and auxiliary equipment are determined by the fluid, capacity, line conditions and required outlet quality.",
    "چه اطلاعاتی برای انتخاب و ساخت لازم است؟": "What Information Is Required for Selection and Manufacture?",
    "برای انتخاب دقیق، نوع محصول، دبی واقعی خط، دما، میزان کدورت یا بار ذرات، کیفیت خروجی مورد انتظار، زمان مطلوب هر سیکل، برنامه شست‌وشو و سطح اتوماسیون باید مشخص باشد. ظرفیت دستگاه فقط براساس ظرفیت نامی پمپ انتخاب نمی‌شود.": "Accurate selection requires the product type, actual line flow, temperature, turbidity or solids loading, target outlet quality, preferred cycle duration, cleaning programme and automation level. The unit is not sized solely from the pump nameplate flow.",
    "قیمت کندل فیلتر به چه عواملی وابسته است؟": "What Determines Candle Filter Pricing?",
    "ظرفیت مؤثر، ویژگی سیال، تعداد و ابعاد کندل‌ها، متریال، شیرآلات و ابزار دقیق، سطح اتوماسیون، طراحی لوله‌کشی و تجهیزات جانبی بر قیمت نهایی اثر دارند. صفحه": "Effective capacity, fluid properties, candle count and size, metallurgy, valves and instruments, automation level, pipework design and auxiliary equipment affect the final price. See the",
    "قیمت و سفارش کندل فیلتر": "Candle Filter Pricing & Ordering",
    "چک‌لیست کامل‌تری برای استعلام دارد.": "page for a more complete enquiry checklist.",
    "پرسش‌های متداول": "Frequently Asked Questions",
    "ظرفیت مناسب چگونه انتخاب می‌شود؟": "How Is the Correct Capacity Selected?",
    "براساس دبی واقعی، بار ذرات، زمان مطلوب هر سیکل و زمان شست‌وشو؛ سپس ابعاد و آرایش دستگاه برای شرایط خط طراحی می‌شود.": "Selection is based on actual flow, solids loading, preferred cycle time and cleaning duration; the unit dimensions and arrangement are then engineered for the line.",
    "آیا دستگاه تمام‌اتوماتیک ساخته می‌شود؟": "Is a Fully Automatic System Available?",
    "بله؛ سطح اتوماسیون متناسب با نیاز خط، کنترل فرایند و بودجه پروژه تعیین می‌شود.": "Yes. The automation level is defined around line requirements, process control and project budget.",
    "آیا CIP و Backwash قابل اجراست؟": "Can CIP and Backwash Be Integrated?",
    "بله؛ منطق شست‌وشو و مسیرهای موردنیاز باید متناسب با محصول و طراحی خط در مشخصات نهایی پروژه تعریف شوند.": "Yes. Cleaning logic and the required circuits are defined in the final project specification for the product and line design.",
    "راهنماهای مرتبط": "Related Guides",
    "عوامل قیمت و چک‌لیست استعلام": "Pricing factors and enquiry checklist",
    "راهنمای انتخاب ظرفیت": "Capacity Selection Guide",
    "اصول فنی سایزینگ کندل فیلتر": "Technical candle-filter sizing principles",
    "رفع کدورت نوشیدنی": "Beverage Haze Removal",
    "انتخاب راهکار از روی مسئله خط": "Select a solution from the line challenge",
    "سؤالات متداول": "FAQ",
    "دی‌اریتور آب سرد": "Cold-Water Deaerator",
    "دی‌اریتور آب سرد بهریز مبدل با ایجاد شرایط وکیوم، اکسیژن و گازهای محلول را از آب فرایندی جدا می‌کند. این دستگاه برای آماده‌سازی آب در خطوط نوشابه، آبمیوه، ماءالشعیر و سایر نوشیدنی‌ها طراحی می‌شود و مشخصات نهایی آن متناسب با ظرفیت و شرایط واقعی خط تعیین می‌گردد.": "The Behriz Mobadel cold-water deaerator uses vacuum conditions to remove oxygen and dissolved gases from process water. It prepares water for soft-drink, juice, malt-beverage and other beverage lines, with final specifications engineered around actual capacity and line conditions.",
    "کاهش اکسیژن محلول پیش از ورود آب به فرایند": "Reduce Dissolved Oxygen Before Water Enters the Process",
    "در این سیستم، آب در شرایط کنترل‌شده و تحت وکیوم در تماس با فضای کم‌فشار قرار می‌گیرد تا اکسیژن و گازهای محلول از آن خارج شوند. کاهش اکسیژن محلول به کنترل اکسیداسیون، پایداری طعم و کیفیت محصول و آماده‌سازی مناسب آب برای فرایند تزریق CO₂ کمک می‌کند.": "In this system, water is exposed to a controlled low-pressure environment under vacuum so oxygen and dissolved gases can be removed. Lower dissolved oxygen helps control oxidation, stabilise flavour and product quality, and prepare water for CO₂ injection.",
    "مناسب خطوط تولید نوشیدنی": "For Beverage Production Lines",
    "دی‌اریتور آب سرد برای آماده‌سازی آب فرایندی در خطوط نوشابه گازدار، ماءالشعیر، آبمیوه و دیگر نوشیدنی‌هایی که کنترل اکسیژن محلول در کیفیت محصول اهمیت دارد، طراحی و ساخته می‌شود.": "The cold-water deaerator prepares process water for carbonated soft drinks, malt beverages, juice and other products where dissolved-oxygen control is critical to quality.",
    "مزیت‌های دی‌اریتور بهریز مبدل": "Advantages of the Behriz Mobadel Deaerator",
    "کاهش اکسیژن و گازهای محلول در آب": "Removes oxygen and dissolved gases from water",
    "کمک به پایداری کیفیت و طعم نوشیدنی": "Supports consistent beverage quality and flavour",
    "سازگار با فرایند تزریق CO₂": "Compatible with CO₂ injection processes",
    "عملکرد تمام‌اتوماتیک": "Fully automatic operation",
    "ساخت بهداشتی با استیل 304L یا 316L": "Hygienic 304L or 316L stainless-steel construction",
    "طراحی متناسب با فشار و ظرفیت واقعی خط": "Engineered for actual line pressure and capacity",
    "قابلیت هماهنگی با سیستم CIP کارخانه": "Can be integrated with the plant CIP system",
    "ساخت سفارشی چیدمان، ابزار دقیق و کنترل": "Custom arrangement, instrumentation and controls",
    "۱۵٬۰۰۰ تا ۲۵٬۰۰۰ لیتر در ساعت": "15,000–25,000 L/h",
    "جنس بخش‌های در تماس": "Product-Contact Material",
    "تمام‌اتوماتیک": "Fully Automatic",
    "فرایند جداسازی": "Separation Process",
    "وکیوم، قابل طراحی به‌صورت دومرحله‌ای": "Vacuum, configurable as a two-stage system",
    "اکسیژن محلول خروجی": "Outlet Dissolved Oxygen",
    "تا حدود ۰٫۲ ppm یا نزدیک صفر*": "Down to approximately 0.2 ppm or near zero*",
    "شست‌وشو": "Cleaning",
    "قابل هماهنگی با CIP خط": "Can be integrated with line CIP",
    "*مقدار نهایی اکسیژن خروجی به دمای آب، فشار وکیوم، کیفیت ورودی و پیکربندی پروژه وابسته است. دیتاشیت نهایی پس از بررسی مهندسی صادر می‌شود.": "*Final outlet oxygen depends on water temperature, vacuum pressure, inlet quality and project configuration. The final datasheet is issued after engineering review.",
    "چه اطلاعاتی برای انتخاب دستگاه لازم است؟": "What Information Is Required for Selection?",
    "ظرفیت خط، دمای آب ورودی، مقدار اکسیژن محلول ورودی و هدف خروجی، فشارهای در دسترس، برنامه شست‌وشو، محدودیت فضای نصب و نیازهای ابزار دقیق باید پیش از طراحی مشخص شوند.": "Line capacity, inlet-water temperature, inlet and target dissolved oxygen, available pressures, cleaning programme, installation-space constraints and instrumentation requirements must be defined before design.",
    "قیمت دی‌اریتور به چه عواملی وابسته است؟": "What Determines Deaerator Pricing?",
    "ظرفیت، تعداد مراحل جداسازی، متریال، پمپ وکیوم، ابزار دقیق، سطح اتوماسیون، شیرآلات، تجهیزات جانبی و محدوده نصب بر قیمت نهایی اثر دارند.": "Capacity, separation stages, metallurgy, vacuum pump, instrumentation, automation, valves, auxiliary equipment and installation scope determine the final price.",
    "مونوپمپ صنایع غذایی": "Food-Grade Progressing Cavity Pump",
    "انتقال آرام سیالات غلیظ": "Gentle transfer of viscous fluids",
    "مونوپمپ بهریز مبدل یک پمپ جابجایی مثبت برای انتقال یکنواخت و آرام سیالات غلیظ و حساس است. این تجهیز برای محصولاتی مانند کنسانتره، شربت، سس، عسل، گلوکز، رب و لبنیات ساخته می‌شود و سایز، دور و متریال آن براساس رفتار واقعی سیال انتخاب می‌گردد.": "The Behriz Mobadel progressing cavity pump is a positive-displacement pump for smooth, consistent transfer of viscous and sensitive fluids. It is manufactured for products such as concentrates, syrups, sauces, honey, glucose, tomato paste and dairy, with size, speed and materials selected from actual fluid behaviour.",
    "انتقال کنترل‌شده سیالات غلیظ و حساس": "Controlled Transfer of Viscous and Sensitive Fluids",
    "در مونوپمپ، چرخش روتور داخل استاتور حفره‌هایی پیوسته ایجاد می‌کند که سیال را با دبی یکنواخت در مسیر پیش می‌برند. این سازوکار، ضربان و تنش برشی را نسبت به بسیاری از روش‌های پمپاژ کاهش می‌دهد و برای انتقال محصولات ویسکوز یا حساس مناسب است.": "Inside a progressing cavity pump, rotor movement within the stator creates continuous cavities that move fluid at a uniform rate. This mechanism reduces pulsation and shear compared with many pumping methods, making it suitable for viscous or sensitive products.",
    "مناسب صنایع غذایی، نوشیدنی و لبنی": "For Food, Beverage & Dairy Processing",
    "این پمپ برای انتقال کنسانتره و عصاره مالت، شربت، سس، رب، عسل، گلوکز، خامه، ماست، دوغ و دیگر محصولات با ویسکوزیته متوسط تا بالا، پس از بررسی فنی سیال و شرایط خط، طراحی و ساخته می‌شود.": "The pump is designed and manufactured for concentrates, malt extract, syrup, sauces, tomato paste, honey, glucose, cream, yoghurt, doogh and other medium- to high-viscosity products after technical review of the fluid and line conditions.",
    "مزیت‌های مونوپمپ بهریز مبدل": "Advantages of the Behriz Mobadel Progressing Cavity Pump",
    "مناسب انتقال سیالات با ویسکوزیته بالا": "Suitable for high-viscosity fluids",
    "دبی یکنواخت و انتقال آرام محصول": "Uniform flow and gentle product transfer",
    "تنش برشی کمتر برای محصولات حساس": "Lower shear for sensitive products",
    "قابلیت انتخاب دور متناسب با محصول": "Product-specific operating-speed selection",
    "ساخت بهداشتی برای صنایع غذایی": "Hygienic food-industry construction",
    "امکان طراحی ورودی متناسب با تغذیه سیال": "Inlet design matched to product feeding",
    "تنوع سایز برای ظرفیت‌های مختلف": "Multiple sizes for different capacities",
    "انتخاب روتور، استاتور و آب‌بندی براساس سیال": "Fluid-specific rotor, stator and seal selection",
    "نوع پمپ": "Pump Type",
    "۱ تا ۲۵ تن در ساعت": "1–25 t/h",
    "سایزهای قابل ساخت": "Available Sizes",
    "۱¼ تا ۴ اینچ": "1¼–4 in",
    "متریال بخش‌های در تماس": "Product-Contact Material",
    "استیل بهداشتی، متناسب با نوع سیال": "Hygienic stainless steel, selected for the fluid",
    "کنترل دبی": "Flow Control",
    "قابل تنظیم با دور موتور و اینورتر": "Adjustable by motor speed and VFD",
    "نوع اتصال": "Connection Type",
    "بهداشتی یا صنعتی، متناسب با خط": "Hygienic or industrial, matched to the line",
    "انتخاب استاتور": "Stator Selection",
    "براساس دما و سازگاری شیمیایی سیال": "Based on temperature and chemical compatibility",
    "مشخصات نهایی موتور، گیربکس، دور، فشار، جنس روتور و استاتور پس از اعلام ویسکوزیته، دما، دبی و فشار خط تعیین می‌شوند.": "Final motor, gearbox, speed, pressure, rotor and stator specifications are determined after viscosity, temperature, flow and line pressure are provided.",
    "چه اطلاعاتی برای انتخاب مونوپمپ لازم است؟": "What Information Is Required to Select the Pump?",
    "نام و ترکیب محصول، دبی هدف، ویسکوزیته در دمای کار، دمای سیال، فشار ورودی و خروجی، وجود ذرات جامد، حساسیت محصول به برش، روش شست‌وشو و ساعات کار روزانه باید مشخص شوند.": "Specify product name and composition, target flow, viscosity at operating temperature, fluid temperature, inlet and outlet pressure, solid particles, shear sensitivity, cleaning method and daily operating hours.",
    "قیمت مونوپمپ به چه عواملی وابسته است؟": "What Determines Progressing Cavity Pump Pricing?",
    "ظرفیت، فشار کاری، سایز، متریال، نوع استاتور و آب‌بندی، موتور و گیربکس، اینورتر، نوع اتصالات و تجهیزات جانبی بر قیمت نهایی اثر دارند.": "Capacity, operating pressure, size, metallurgy, stator and seal type, motor and gearbox, VFD, connections and auxiliary equipment determine the final price.",
    "کاهش اکسیژن محلول آب": "Dissolved-oxygen reduction",
    "ارتباط مستقیم با تیم مهندسی": "Direct Contact with Our Engineering Team",
    "از یک تماس، تا یک": "From One Conversation to a",
    "راهکار صنعتی دقیق.": "Precise Industrial Solution.",
    "برای انتخاب تجهیز، استعلام قیمت یا بررسی مشخصات خط تولید، مستقیم با تیم بهریز مبدل در ارتباط باشید.": "Contact the Behriz Mobadel team directly for equipment selection, pricing or a review of your production-line requirements.",
    "تماس مستقیم": "Call Directly",
    "گفت‌وگوی سریع": "Quick Conversation",
    "واتس‌اپ بهریز مبدل": "Behriz Mobadel WhatsApp",
    "پاسخ‌گویی تلفنی": "Phone Support",
    "شنبه تا پنجشنبه، ساعت ۸ تا ۱۶": "Saturday–Thursday, 08:00–16:00",
    "موقعیت مجموعه": "Facility Location",
    "شهرک صنعتی": "Industrial Estate",
    "پرند": "Parand",
    "دفتر مرکزی و کارخانه": "Head Office & Factory",
    "یک مجموعه، یک موقعیت مشترک": "One facility, one shared location",
    "بلوار گلستان شرقی": "East Golestan Blvd.",
    "خیابان گلبهار": "Golbahar St.",
    "نشانی کارخانه و دفتر مرکزی": "Factory & Head Office Address",
    "انتخاب مسیریاب": "Choose Navigation App",
    "راه‌های ارتباطی": "Contact Channels",
    "هر مسیری که برای شما سریع‌تر است.": "Choose the Channel That Works Best for You.",
    "تماس با دفتر": "Call the Office",
    "برای مشاوره فنی، استعلام و هماهنگی بازدید": "Technical advice, enquiries and visit coordination",
    "واتس‌اپ": "WhatsApp",
    "ارسال مشخصات پروژه": "Send Project Requirements",
    "تصویر، ظرفیت و اطلاعات خط را مستقیم ارسال کنید": "Send images, capacity and line details directly",
    "اینستاگرام": "Instagram",
    "محصولات، پروژه‌ها و پشت صحنه ساخت تجهیزات": "Products, projects and behind-the-scenes manufacturing",
    "ایمیل": "Email",
    "ارسال مدارک فنی، نقشه‌ها و درخواست رسمی": "Send technical documents, drawings and formal enquiries",
    "مشخصات خط را بفرستید؛": "Send Your Line Requirements;",
    "تیم ما مسیر فنی را بررسی می‌کند.": "Our Team Will Review the Technical Route.",
    "ارسال مشخصات در واتس‌اپ ←": "Send Requirements via WhatsApp →",
    "شهرک صنعتی پرند، خیابان گلبهار، پلاک ۷": "No. 7, Golbahar St., Parand Industrial Estate",
    "مسیریابی به مجموعه بهریز مبدل": "Navigate to Behriz Mobadel",
    "با کدام مسیریاب باز شود؟": "Choose a Navigation App",
    "موقعیت مشترک دفتر مرکزی و کارخانه در شهرک صنعتی پرند": "Shared head-office and factory location in Parand Industrial Estate",
    "گوگل مپ": "Google Maps",
    "ویز": "Waze",
    "نشان": "Neshan",
    "بلد": "Balad",
    "تجهیزات فرایندی": "Process Equipment",
    "راهنمای انتخاب و محاسبه ظرفیت مخزن استیل صنایع غذایی": "Food-Grade Stainless-Steel Tank Sizing Guide",
    "راهکار جامع": "Integrated Solution",
    "طراحی سیستم فیلتراسیون نوشیدنی": "Beverage Filtration System Engineering",
    "طراحی و ساخت خط تولید نوشیدنی": "Beverage Production-Line Design & Manufacture",
    "محصول تخصصی": "Specialist Product",
    "مخازن فرایندی": "Process Tanks",
    "مشاهده راهکار ←": "View Solution →",
    "مشاهده محصول ←": "View Product →",
    "کندل فیلتر صنعتی؛ مشخصات و سفارش": "Industrial Candle Filter: Specifications & Ordering",
    "باز کردن منو": "Open Menu",
    "بهریز مبدل": "Behriz Mobadel",
    "لوگوی بهریز مبدل": "Behriz Mobadel Logo",
    "ناوبری اصلی": "Main Navigation",
    "تجهیزات منتخب بهریز مبدل": "Featured Behriz Mobadel Equipment",
    "سیستم فرایندی بهریز مبدل": "Behriz Mobadel Process System",
    "فیلتر کارتریج استنلس استیل": "Stainless-Steel Cartridge Filter",
    "مثلاً آبمیوه، شربت یا ماءالشعیر": "e.g. juice, syrup or malt beverage",
    "مشاهده کندل فیلتر": "View Candle Filter",
    "صفحه اصلی بهریز مبدل": "Behriz Mobadel Home",
    "بستن": "Close",
    "بستن پنجره انتخاب مسیریاب": "Close Navigation-App Dialog",
    "نقشه موقعیت کارخانه و دفتر مرکزی بهریز مبدل": "Behriz Mobadel Factory and Head Office Location Map",
    "نقشه گرافیکی موقعیت دفتر مرکزی و کارخانه بهریز مبدل در شهرک صنعتی پرند": "Illustrated map of the Behriz Mobadel head office and factory in Parand Industrial Estate",
    "کندل فیلتر صنعتی ساخت بهریز مبدل": "Industrial Candle Filter Manufactured by Behriz Mobadel",
    "دی‌اریتور آب سرد واقعی ساخت بهریز مبدل": "Behriz Mobadel Cold-Water Deaerator",
    "مونوپمپ صنایع غذایی واقعی ساخت بهریز مبدل": "Behriz Mobadel Food-Grade Progressing Cavity Pump",
    "مشاهده خدمات خط تولید نوشیدنی": "View Beverage Production-Line Services",
    "مشاهده راهکار فیلتراسیون نوشیدنی": "View Beverage Filtration Solution",
    "مشاهده صفحه کندل فیلتر صنعتی": "View Industrial Candle Filter Page",
    "مطالعه راهنمای CIP و Backwash": "Read the CIP and Backwash Guide",
    "مطالعه راهنمای انتخاب کندل فیلتر": "Read the Candle Filter Selection Guide",
    "مطالعه راهنمای محاسبه ظرفیت مخزن استیل": "Read the Stainless-Steel Tank Sizing Guide",
    "مطالعه مقایسه استیل 304L و 316L": "Read the 304L vs 316L Stainless-Steel Comparison",
    "بررسی نقشه مهندسی و کنترل ساخت اسکید فرایندی بهریز مبدل": "Engineering drawing review and process-skid manufacturing inspection",
    "مهندسان بهریز مبدل در حال بررسی تجهیزات فرایندی": "Behriz Mobadel engineers reviewing process equipment",
    "نصب و راه‌اندازی تجهیزات فرایندی بهریز مبدل": "Installation and commissioning of Behriz Mobadel process equipment",
    "کندل فیلتر واقعی ساخت بهریز مبدل": "Behriz Mobadel Industrial Candle Filter",
    "راهکارها": "Solutions",
    "محصولات": "Products",
    "درباره ما": "About Us",
    "پروژه‌ها": "Projects",
    "توانمندی‌ها": "Capabilities",
    "دانش فنی": "Technical Knowledge",
    "تماس با ما": "Contact",
    "درخواست فنی": "Request a Consultation",
    "خانه": "Home",
    "مهندسی شفافیت": "Engineering Clarity",
    "در خط تولید": "Across Your Production Line",
    "طراحی و ساخت سیستم‌های فیلتراسیون و تجهیزات فرایندی برای صنایع غذایی و نوشیدنی؛ متناسب با محصول، ظرفیت و شرایط واقعی خط تولید شما.": "Filtration systems and process equipment engineered for food and beverage production—tailored to your product, capacity, and real operating conditions.",
    "شروع بررسی فنی": "Start a Technical Review",
    "مشاهده راهکارها": "Explore Solutions",
    "مهندسی سفارشی": "Custom Engineering",
    "ساخت ایران": "Made in Iran",
    "لیتر در ساعت": "litres per hour",
    "بیش از دو دهه": "Over Two Decades",
    "تجربه تخصصی": "Specialist Experience",
    "طراحی بهداشتی": "Hygienic Design",
    "برای صنایع غذایی": "For Food Processing",
    "ساخت سفارشی": "Custom-Built",
    "براساس ظرفیت خط": "For Your Line Capacity",
    "پشتیبانی فنی": "Technical Support",
    "از طراحی تا راه‌اندازی": "From Design to Commissioning",
    "از مسئله تا راهکار": "From Challenge to Solution",
    "مسیر فرایند را انتخاب کنید": "Choose Your Process Stage",
    "روی هر مرحله بزنید تا راهکار و تجهیزات مرتبط با آن را ببینید.": "Select a stage to explore the relevant solution and equipment.",
    "آماده‌سازی آب": "Water Preparation",
    "اختلاط و فرمولاسیون": "Mixing & Formulation",
    "دی‌اریشن": "Deaeration",
    "فیلتراسیون": "Filtration",
    "پاستوریزاسیون": "Pasteurisation",
    "مرحله ۰۴": "Stage 04",
    "راهکار فیلتراسیون": "Filtration Solution",
    "شفافیت پایدار، بدون توقف خط": "Consistent Clarity Without Line Stoppages",
    "کندل فیلترهای بهریز مبدل برای شفاف‌سازی نوشیدنی‌ها در ظرفیت‌های مختلف طراحی می‌شوند؛ با قابلیت اجرای دستی یا اتوماتیک و امکان شست‌وشوی CIP و Backwash.": "Behriz Mobadel candle filters clarify beverages across a wide capacity range, with manual or automatic operation and integrated CIP and backwash capability.",
    "متریال": "Material",
    "ظرفیت": "Capacity",
    "اجرا": "Operation",
    "دستی و اتوماتیک": "Manual & Automatic",
    "دریافت پیشنهاد فنی": "Request a Technical Proposal",
    "دریافت پیشنهاد فنی ←": "Request a Technical Proposal →",
    "راهکار آماده‌سازی آب": "Water Preparation Solution",
    "آب پایدار برای یک فرایند پایدار": "Reliable Water for a Reliable Process",
    "آماده‌سازی آب ورودی متناسب با کیفیت آب و نیاز خط، پایه عملکرد مطمئن تجهیزات پایین‌دست است.": "Preparing the incoming water for its actual quality and process requirements is the foundation of reliable downstream performance.",
    "هدف": "Objective",
    "طراحی": "Design",
    "متناسب با خط": "Line-Specific",
    "یکپارچگی": "Integration",
    "با تجهیزات موجود": "With Existing Equipment",
    "راهکار اختلاط": "Mixing Solution",
    "فرمولاسیون دقیق و تکرارپذیر": "Precise, Repeatable Formulation",
    "میکسرهای فرایندی، آزمایشگاهی و هموژنایزر برای دستیابی به اختلاط یکنواخت و کیفیت پایدار محصول.": "Process mixers, laboratory mixers, and homogenisers engineered for uniform blending and consistent product quality.",
    "کاربرد": "Application",
    "غذایی و نوشیدنی": "Food & Beverage",
    "راهکار دی‌اریشن آب سرد": "Cold-Water Deaeration Solution",
    "حذف اکسیژن محلول، حفظ کیفیت نوشیدنی": "Remove Dissolved Oxygen, Preserve Beverage Quality",
    "دی‌اریتور آب سرد بهریز مبدل با فرایند وکیوم، اکسیژن و گازهای محلول را از آب جدا می‌کند؛ راهکاری تمام‌اتوماتیک برای خطوط نوشابه، آبمیوه، ماءالشعیر و سایر نوشیدنی‌های گازدار.": "Behriz Mobadel cold-water deaerators use vacuum processing to remove oxygen and dissolved gases—providing a fully automatic solution for soft drinks, juices, malt beverages, and other carbonated products.",
    "کنترل": "Control",
    "تمام‌اتوماتیک": "Fully Automatic",
    "راهکار پاستوریزاسیون": "Pasteurisation Solution",
    "کنترل حرارتی در فضای کمتر": "Thermal Control in a Smaller Footprint",
    "تونل پاستوریزه اسپیرال برای فرایند حرارتی پیوسته با طراحی کم‌جا و قابلیت تطبیق با ظرفیت خط.": "A compact spiral tunnel pasteuriser for continuous thermal processing, engineered to match the production-line capacity.",
    "ساختار": "Configuration",
    "اسپیرال کم‌جا": "Compact Spiral",
    "از سال ۱۳۷۷": "Since 1998",
    "درباره بهریز مبدل": "About Behriz Mobadel",
    "بیش از دو دهه طراحی و ساخت تجهیزات فرایندی": "Over Two Decades of Process Equipment Engineering",
    "شرکت تولیدی صنعتی بهریز مبدل برای طراحی و ساخت تجهیزات و ماشین‌آلات خطوط تولید صنایع غذایی و نوشیدنی تأسیس شد و در ادامه، فعالیت تخصصی خود را در تولید مونوپمپ، فیلترهای صفحه‌ای و کندل فیلترهای مبتنی بر نمونه‌های معتبر اروپایی توسعه داد.": "Behriz Mobadel was founded to design and manufacture equipment for food and beverage production lines, later developing specialist expertise in progressing cavity pumps, plate filters, and candle filters inspired by established European systems.",
    "امروز این شرکت مجموعه‌ای کامل از تجهیزات فیلتراسیون، پمپاژ، اختلاط، دی‌اریشن، انتقال مواد، پاستوریزاسیون، مخازن و سیستم‌های شست‌وشو را متناسب با شرایط صنعت ایران طراحی و تولید می‌کند.": "Today, the company engineers a complete portfolio of filtration, pumping, mixing, deaeration, conveying, pasteurisation, tank, and cleaning systems for demanding industrial applications.",
    "داستان بهریز مبدل": "Our Story",
    "داستان بهریز مبدل ←": "Our Story →",
    "مشتریان بهریز مبدل": "Behriz Mobadel Clients",
    "اعتماد برندهای پیشرو صنعت ایران": "Trusted by Leading Industrial Brands",
    "تجهیزات و راهکارهای بهریز مبدل در خطوط تولید مجموعه‌های مطرح صنایع غذایی و نوشیدنی ایران به کار گرفته شده‌اند.": "Behriz Mobadel equipment and process solutions operate in leading food and beverage production facilities.",
    "محصولات منتخب": "Featured Equipment",
    "تجهیزات کلیدی برای خطوط فرایندی": "Core Equipment for Process Lines",
    "مشاهده همه محصولات": "View All Products",
    "مشاهده مشخصات": "View Specifications",
    "پروژه و تجربه اجرایی": "Projects & Delivery Experience",
    "مهندسی برای عملکرد واقعی": "Engineering for Real-World Performance",
    "توانمندی‌های مهندسی": "Engineering Capabilities",
    "طراحی، ساخت و پشتیبانی یکپارچه": "Integrated Design, Manufacturing & Support",
    "مرکز دانش": "Knowledge Centre",
    "دانش فنی برای تصمیم‌های بهتر": "Technical Insight for Better Decisions",
    "مطالعه مقاله": "Read Article",
    "شروع همکاری": "Start a Project",
    "برای پروژه بعدی آماده‌اید؟": "Ready for Your Next Project?",
    "مشخصات خط تولید را با تیم مهندسی ما در میان بگذارید.": "Share your process requirements with our engineering team.",
    "نام و نام خانوادگی": "Full name",
    "نوع محصول یا سیال": "Product or fluid",
    "ظرفیت خط": "Line capacity",
    "شماره تماس": "Phone number",
    "ارسال درخواست": "Send Request",
    "آدرس کارخانه": "Factory Address",
    "شهرک صنعتی پرند، میدان توسعه، بلوار گلستان شرقی، انتهای فروزان، خیابان گلبهار، پلاک ۷": "No. 7, Golbahar St., Forouzan, East Golestan Blvd., Tose'e Sq., Parand Industrial Estate, Tehran, Iran",
    "دسترسی سریع": "Quick Links",
    "تجهیزات فرایندی بهریز مبدل": "Behriz Mobadel Process Equipment",
    "مجموعه کامل راهکارهای فیلتراسیون، پمپاژ، اختلاط، انتقال، شست‌وشو و فرایند حرارتی برای صنایع غذایی و نوشیدنی.": "A complete portfolio of filtration, pumping, mixing, conveying, cleaning, and thermal process solutions for food and beverage production.",
    "بیش از دو دهه مهندسی برای صنعت": "Over Two Decades of Engineering for Industry",
    "طراحی و ساخت ماشین‌آلات خط تولید صنایع غذایی و آشامیدنی": "Design and manufacture of food and beverage production-line machinery",
    "درباره شرکت": "About the Company",
    "از ساخت تجهیزات خطوط نوشیدنی تا تخصص در فیلتراسیون": "From Beverage-Line Equipment to Filtration Expertise",
    "شرکت تولیدی صنعتی بهریز مبدل (سهامی خاص) با مدیریت بهمن باباخانی در سال ۱۳۷۷ برای طراحی و ساخت تجهیزات و ماشین‌آلات خط تولید شربت غلیظ، آبمیوه، ماءالشعیر، انواع نوشابه و لبنیات تأسیس گردید و در سال ۱۳۸۳ با نام جدید شرکت تولیدی صنعتی بهریز مبدل، علاوه بر زمینه فعالیت‌های قبلی، تولید مونوپمپ به سبک نمونه‌های اروپایی و همچنین تولید فیلترهای کیزلگور صفحه‌ای نمونه SCHENCK آلمان را آغاز کرد.": "Behriz Mobadel Industrial Manufacturing Co. was founded in 1998 under the management of Bahman Babakhani to design and manufacture equipment for syrup, juice, malt beverage, soft drink, and dairy production lines. In 2004, the company expanded into progressing cavity pumps and SCHENCK-style kieselguhr plate filters.",
    "در ادامه، طراحی و ساخت فیلترهای جدید و به‌روز اروپایی به‌صورت کندل فیلتر، نمونه فیلترهای KHS آلمان و شرکت FILTROX، برای فیلتراسیون ماءالشعیر و آبمیوه توسعه یافت. با حمایت و تشویق مدیران و فعالان صنعت، این پروژه‌ها به بهره‌برداری رسید و امکان تولید این نوع فیلترها در داخل کشور و بی‌نیازی از نمونه‌های خارجی فراهم شد.": "The company subsequently developed modern candle filtration systems based on established KHS and FILTROX concepts for malt beverage and juice applications. Successful industrial deployment established a reliable local manufacturing alternative to imported filtration equipment.",
    "این شرکت با همکاری یکی از شرکت‌های معتبر آلمانی، در ساخت دی‌اریتور آب سرد نمونه FAMIX نیز موفق بوده است. بهریز مبدل عضو انجمن صنفی کارفرمایی ماشین‌سازان صنایع غذایی ایران است؛ انجمنی که با هدف بهبود وضعیت اقتصادی و ارتقای توانمندی‌های صنعتگران و تولیدکنندگان این صنعت فعالیت می‌کند.": "Working with an established German engineering company, Behriz Mobadel also developed a FAMIX-style cold-water deaerator. The company is a member of Iran’s Food Industry Machinery Manufacturers Association.",
    "مهندسی برای صنعت": "Engineering for Industry",
    "تخصص محوری": "Focused Expertise",
    "جایگزینی واردات": "Local Manufacturing",
    "طراحی سفارشی": "Custom Design",
    "ساخت و پشتیبانی": "Manufacturing & Support",
    "تمرکز عمیق بر فیلتراسیون و تجهیزات فرایندی خطوط غذایی و نوشیدنی.": "Deep expertise in filtration and process equipment for food and beverage lines.",
    "ساخت داخلی تجهیزات مبتنی بر نمونه‌های معتبر اروپایی و متناسب با صنعت ایران.": "Locally manufactured equipment informed by proven European systems.",
    "طراحی هر تجهیز براساس محصول، ظرفیت و شرایط واقعی خط تولید.": "Every system is engineered around the product, capacity, and actual line conditions.",
    "همراهی از تحلیل نیاز و ساخت تا نصب، راه‌اندازی و خدمات فنی.": "Support from requirements analysis and manufacturing through installation, commissioning, and service.",
    "برای پروژه بعدی آماده‌اید؟": "Ready for Your Next Project?",
    "مشخصات خط تولید را با تیم مهندسی ما در میان بگذارید.": "Share your production requirements with our engineering team.",
    "شروع بررسی فنی": "Start a Technical Review",
    "همه": "All",
    "پمپ و انتقال": "Pumps & Transfer",
    "انتقال مواد": "Material Handling",
    "فرایند حرارتی": "Thermal Processing",
    "مخازن": "Tanks",
    "شست‌وشو": "Cleaning Systems",
    "میکسر": "Mixers",
    "دوزینگ": "Dosing",
    "تجهیزات جانبی": "Auxiliary Equipment",
    "مشاهده مشخصات کامل": "View Full Specifications",
    "سبد کامل تجهیزات": "Complete Equipment Portfolio",
    "محصولات بهریز مبدل": "Behriz Mobadel Equipment",
    "تجهیزات تخصصی خطوط غذایی و نوشیدنی، طراحی‌شده متناسب با ظرفیت و فرایند شما.": "Specialist food and beverage equipment engineered around your capacity and process.",
    "نمایش همه محصولات": "View All Products",
    "کندل فیلتر": "Candle Filter",
    "فیلتر کارتریج تک": "Single Cartridge Filter",
    "دی‌اریتور آب سرد": "Cold-Water Deaerator",
    "مونوپمپ": "Progressing Cavity Pump",
    "تونل پاستوریزه اسپیرال": "Spiral Tunnel Pasteuriser",
    "مخازن استنلس استیل": "Stainless-Steel Tanks",
    "سیستم CIP": "CIP System",
    "میکسر هموژنایزر": "Homogeniser Mixer",
    "مشاهده مشخصات فنی": "View Specifications",
    "مشاهده مشخصات فنی ←": "View Specifications →",
    "ظرفیت ۴٬۰۰۰ تا ۴۰٬۰۰۰ لیتر در ساعت": "Capacity: 4,000–40,000 litres per hour",
    "ظرفیت ۱۰٬۰۰۰ تا ۳۵٬۰۰۰ لیتر در ساعت": "Capacity: 10,000–35,000 litres per hour",
    "ظرفیت ۱۵٬۰۰۰ تا ۲۵٬۰۰۰ لیتر در ساعت": "Capacity: 15,000–25,000 litres per hour",
    "ظرفیت ۲٬۰۰۰ تا ۲۰٬۰۰۰ لیتر در ساعت": "Capacity: 2,000–20,000 litres per hour",
    "ظرفیت ۵۰ تا ۵۰٬۰۰۰ لیتر در ساعت": "Capacity: 50–50,000 litres per hour",
    "۴٬۰۰۰ تا ۴۰٬۰۰۰ L/H": "4,000–40,000 L/H",
    "انتقال سیالات غلیظ در سایزهای مختلف": "Transfer of viscous fluids across multiple sizes",
    "تک‌جداره، دوجداره و سه‌جداره": "Single-, double-, and triple-wall configurations",
    "قابل ساخت در مدل دستی و اتوماتیک": "Available in manual and automatic configurations",
    "مطالعه مقاله ←": "Read Article →",
    "ارسال برای بررسی فنی ←": "Submit for Technical Review →",
    "اختلاط": "Mixing",
    "سوابق اجرایی": "Project Experience",
    "تجربه اجرا در ایران": "Delivery Experience in Iran",
    "و بازارهای منطقه": "and Regional Markets",
    "سابقه طراحی، ساخت، نصب و راه‌اندازی تجهیزات فرایندی برای کارخانه‌های صنایع غذایی و آشامیدنی در ایران، افغانستان و عراق.": "Experience designing, manufacturing, installing, and commissioning process equipment for food and beverage plants in Iran, Afghanistan, and Iraq.",
    "پروژه مستند کندل فیلتر": "Documented Candle Filter Projects",
    "بیش از ۲۶ پروژه": "More Than 26 Projects",
    "دامنه خدمات": "Scope of Service",
    "طراحی تا راه‌اندازی": "Design to Commissioning",
    "مشاوره پروژه جدید": "Discuss a New Project",
    "اعتبار فنی": "Technical Credentials",
    "استانداردها و صلاحیت‌های تخصصی": "Standards & Specialist Qualifications",
    "کنترل کیفیت ساخت و آزمون‌های تخصصی، بخشی از فرایند تحویل تجهیزات بهریز مبدل است.": "Manufacturing quality control and specialist inspection form part of every Behriz Mobadel delivery.",
    "سیستم مدیریت کیفیت": "Quality Management System",
    "عضو انجمن ماشین‌سازان صنایع غذایی ایران": "Member of Iran’s Food Machinery Manufacturers Association",
    "صلاحیت آزمون‌های غیرمخرب سطح": "Surface Non-Destructive Testing Qualification",
    "صلاحیت آزمون‌های رادیوگرافی و فراصوت": "Radiographic & Ultrasonic Testing Qualification",
    "توان ساخت": "Manufacturing Capability",
    "مهندسی که به عملکرد می‌رسد": "Engineering That Delivers",
    "از تحلیل نیاز تا ساخت، کنترل کیفیت، نصب و پشتیبانی.": "From requirements analysis through manufacturing, quality control, installation, and support.",
    "نیازسنجی و تحلیل فرایند": "Requirements & Process Analysis",
    "بررسی محصول، ظرفیت، فضای نصب و هدف فرایندی": "Review of product, capacity, installation space, and process objective",
    "طراحی مهندسی": "Engineering Design",
    "انتخاب راهکار و طراحی متناسب با خط": "Solution selection and line-specific design",
    "ساخت و کنترل کیفیت": "Manufacturing & Quality Control",
    "ساخت استیل، مونتاژ و تست عملکرد": "Stainless fabrication, assembly, and performance testing",
    "نصب و راه‌اندازی": "Installation & Commissioning",
    "تحویل، آموزش و پشتیبانی فنی": "Handover, training, and technical support",
    "دانش فنی برای تصمیم بهتر": "Technical Knowledge for Better Decisions",
    "کندل فیلتر چیست و چگونه ظرفیت مناسب را انتخاب کنیم؟": "What Is a Candle Filter and How Should Capacity Be Selected?",
    "تفاوت استیل AISI 304L و 316L در صنایع غذایی": "AISI 304L vs 316L Stainless Steel in Food Processing",
    "نگهداری": "Maintenance",
    "اصول شست‌وشوی CIP و Backwash در سیستم فیلتراسیون": "CIP and Backwash Principles for Filtration Systems",
    "شروع یک پروژه": "Start a Project",
    "مشخصات خط تولیدتان را": "Share Your Production Requirements",
    "با مهندسان ما در میان بگذارید.": "with Our Engineering Team",
    "برای دریافت پیشنهاد اولیه، نوع محصول و ظرفیت خط را ثبت کنید.": "Provide the product and line capacity for an initial technical review.",
    "ارسال برای بررسی فنی": "Submit for Technical Review",
    "ارتباط با ما": "Contact Us",
    "واتساپ و مشاوره فنی": "WhatsApp & Technical Consultation",
    "تماس: ۸ تا ۱۶ | واتساپ: ۲۴ ساعته": "Calls: 08:00–16:00 | WhatsApp: 24/7",
    "طراحی و ساخت سیستم‌های فیلتراسیون و تجهیزات فرایندی صنایع غذایی و نوشیدنی از سال ۱۳۷۷": "Engineering and manufacturing filtration systems and process equipment for the food and beverage industry since 1998.",
    "۰۲۱ ۵۶۴۱ ۷۴۹۴": "+98 21 5641 7494",
    "در حال انتقال به واتساپ…": "Opening WhatsApp…",
    "محصول": "Product",
    "مشخصات فنی تجهیزات فرایندی و ماشین‌آلات صنایع غذایی ساخت بهریز مبدل.": "Technical specifications for Behriz Mobadel food and beverage process equipment.",
    "راهنمای انتخاب کندل فیلتر": "Candle Filter Selection Guide",
    "تفاوت استنلس استیل 304L و 316L": "Stainless Steel 304L vs 316L",
    "راهنمای CIP و Backwash": "CIP & Backwash Guide",
    "بازگشت به مرکز دانش": "Back to Knowledge Centre"
  }));

  const normaliseText = (value) => value.replace(/\s+/g, " ").trim();

  const replaceText = (root = document.body) => {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach((node) => {
      const raw = node.nodeValue;
      const key = normaliseText(raw);
      if (!key) return;
      const translated = translations.get(key);
      if (translated) node.nodeValue = raw.replace(raw.trim(), translated);
    });
  };

  document.documentElement.lang = "en";
  document.documentElement.dir = "ltr";
  document.body.classList.add("lang-en");
  replaceText();

  document.querySelectorAll("[alt],[aria-label],[placeholder]").forEach((el) => {
    ["alt", "aria-label", "placeholder"].forEach((attr) => {
      const value = el.getAttribute(attr);
      const key = value ? normaliseText(value) : "";
      if (key && translations.has(key)) {
        el.setAttribute(attr, translations.get(key));
      } else if (/^لوگوی مشتری \d+$/.test(key)) {
        el.setAttribute(attr, key.replace("لوگوی مشتری", "Client logo"));
      } else if (key.startsWith("مشاهده ")) {
        el.setAttribute(attr, key.replace("مشاهده ", "View "));
      } else if (key.startsWith("مطالعه ")) {
        el.setAttribute(attr, key.replace("مطالعه ", "Read "));
      }
    });
  });

  const translationObserver = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      mutation.addedNodes.forEach((node) => {
        if (node.nodeType === Node.TEXT_NODE) {
          const key = normaliseText(node.nodeValue || "");
          if (translations.has(key)) node.nodeValue = translations.get(key);
        } else if (node.nodeType === Node.ELEMENT_NODE) {
          replaceText(node);
        }
      });
    });
  });
  translationObserver.observe(document.body, { childList: true, subtree: true });

  document.querySelectorAll("a[href]").forEach((a) => {
    const href = a.getAttribute("href");
    if (!href || href.startsWith("#") || /^(https?:|tel:|mailto:|javascript:)/.test(href)) return;
    if (/^(index|about|products|product|contact|candle-filter|cold-water-deaerator|mono-pump|candle-filter-guide|stainless-steel-304l-vs-316l|cip-backwash-guide)\.html/.test(href)) {
      a.setAttribute("href", `en/${href}`);
    }
  });

  if (/\/en\/contact\.html$/.test(location.pathname)) {
    const contactMessage = encodeURIComponent("Hello, I would like a technical consultation with Behriz Mobadel.");
    const projectMessage = encodeURIComponent("Hello,\nProduct or fluid:\nLine capacity:\nProject details:");
    document.querySelectorAll('a[href*="wa.me"]').forEach((link) => {
      link.href = `https://wa.me/982156417494?text=${link.closest(".contact-final") ? projectMessage : contactMessage}`;
    });
  }

  document.querySelectorAll(".lang").forEach((button) => {
    button.textContent = "FA";
    button.setAttribute("aria-label", "Persian version");
    button.addEventListener("click", () => { location.href = persianUrl; });
  });

  addEventListener("DOMContentLoaded", () => {
    const contact = document.querySelector(".floating-contact");
    if (contact) {
      contact.setAttribute("aria-label", "Quick contact options");
      const labels = contact.querySelectorAll("span");
      if (labels[0]) labels[0].textContent = "Call Us";
      if (labels[1]) labels[1].textContent = "WhatsApp";
      const whatsapp = contact.querySelector('[href*="wa.me"]');
      if (whatsapp) whatsapp.href = `https://wa.me/982156417494?text=${encodeURIComponent("Hello, I would like a technical consultation with Behriz Mobadel.")}`;
    }
    const actions = document.querySelector(".nav-actions");
    if (actions && !actions.querySelector(".language-switch") && !actions.querySelector(".lang")) {
      const link = document.createElement("a");
      link.className = "lang language-switch";
      link.href = persianUrl;
      link.textContent = "FA";
      link.setAttribute("aria-label", "Persian version");
      actions.prepend(link);
    }
  });
})();
